services:
###> doctrine/doctrine-bundle ###
  # database_test:
  #   image: mysql:8.4
  #   container_name: database_test
  #   environment:
  #     MYSQL_ROOT_PASSWORD: symfony
  #     MYSQL_DATABASE: symfony_test
  #   ports: 
  #     - 3306
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    container_name: mailer
    ports: [1025, 1080]
###< symfony/mailer ###
